#!/bin/bash
for ((i=0; i<26; i++)); do for ((j=0; j<26; j++)); do letter1=$(printf "\x$(printf "%x" $((97+i)))"); letter2=$(printf "\x$(printf "%x" $((97+j)))"); [ "$letter1$letter2" != "oo" ] && echo "$letter1$letter2"; done; done

